Site/Site/Controllers/PlanoController.cs
using Site.Filters;
using Site.Models;
using Site.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Site.Controllers
{
    //[PaginaParaUsuarioLogado]
    public class PlanoController : Controller
    {
        private readonly IPlanoRepositorio _planoRepositorio;

        public PlanoController(IPlanoRepositorio planoRepositorio)
        {
            _planoRepositorio = planoRepositorio;
        }

        public IActionResult Index()
        {
            List<PlanoModel> planos = _planoRepositorio.BuscarTodos();

            return  View(planos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            PlanoModel plano = _planoRepositorio.BuscarPorID(id);
            return View(plano);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            PlanoModel plano = _planoRepositorio.BuscarPorID(id);
            return View(plano);
        }
        public IActionResult Apagar(int id)
            {
                try
                {
                    bool apagado = _planoRepositorio.Apagar(id);

                    if (apagado) TempData["MensagemSucesso"] = "Contato apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu contato, tente novamante!";
                    return RedirectToAction("Index");
                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                    return RedirectToAction("Index");
                }
            }

            [HttpPost]
            public IActionResult Criar(PlanoModel planos)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                    planos = _planoRepositorio.Adicionar(planos);

                        TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                        return RedirectToAction("Index");
                    }

                    return View(planos);
                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                    return RedirectToAction("Index");
                }
            }

            [HttpPost]
            public IActionResult Editar(PlanoModel planos)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        planos = _planoRepositorio.Atualizar(planos);
                        TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                        return RedirectToAction("Index");
                    }

                    return View(planos);
                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                    return RedirectToAction("Index");
                }
            }
        }
    } 

Site/Site/Views/Plano/ApagarConfirmacao.cshtml
@model PlanoModel
@{
    ViewData["Title"] = "Confirmação apagar contato";
}

<div class="text-center">
    <h3>Realmente deseja apagar o plano (@Model.Plano)?</h3>
</div>

<a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Plano" role="button">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-action="Apagar" asp-controller="Plano" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

Site/Site/Views/Plano/Criar.cshtml
@model PlanoModel
@{
    ViewData["Title"] = "Criar contato";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar Planos</h1>
</div>


<form asp-controller="Plano" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Plano</label>
        <input type="text" asp-for="Plano" class="form-control" placeholder="Digite o plano">
        @Html.ValidationMessageFor(x => x.Plano)
    </div>

    <div class="form-group">
        <label for="valor" class="form-label">Valor</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor">
        @Html.ValidationMessageFor(x => x.Valor)
    </div>

     <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Plano" role="button">Voltar</a>

</form>

Site/Site/Views/Plano/Editar.cshtml
@model PlanoModel

@{
    ViewData["Title"] = "Editar contato";
}

<div class="text-center">

    <hi class="display-4">Editar Planos</hi>

</div>

<form asp-controller="Plano" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
 <div class="form-group">
    <label for="Nome">Plano</label>
    <input type="text" asp-for="Plano" class="form-control"  placeholder="Digite o plano">
    
  </div>

    <div class="form-group">
    <label for="valor">Valor</label>
    <input type="double" asp-for="Plano" class="form-control"  placeholder="Digite o valor">
    @Html.ValidationMessageFor(x=> x.Plano)
  </div>

  <div class="form-group">
    <label for="valor">Valor</label>
    <input type="double" asp-for="Valor" class="form-control"  placeholder="Digite o valor">
    @Html.ValidationMessageFor(x=> x.Valor)
  </div>

    
  <button type="submit" class="btn btn-primary bnt-block">Alterar</button>
  <a class="btn btn-secondary bnt-block" asp-controller="Plano" asp-action="Index" role="button">Voltar</a>
</form>

Site/Site/Views/Plano/Index.cshtml
@model List<PlanoModel>
@{
    ViewData["Title"] = "Listagem de Planos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" asp-controller="Plano" asp-action="Criar" role="button">Adicionar novo plano</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de planos</h1>

    <table id="table-planos" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Plano</th>
                <th scope="col">Valor</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var plano in Model)
                {
                    <tr>
                        <th scope="row">@plano.Id</th>
                        <td>@plano.Plano</td>
                        <td>@plano.Valor</td>
                        <td>@plano.DataAtualizacao</td>
                        <td>@plano.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Editar" asp-controller="Plano" asp-route-id="@plano.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="ApagarConfirmacao" asp-controller="Plano" asp-route-id="@plano.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum plano encontrado</td></tr>
            }
        </tbody>
    </table>

</div>